# templates/externalsecret.yaml
{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "myapp.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "300s" }}
  secretStoreRef:
    name: {{ .secretStore | default "aws-secrets-manager" }}
    kind: {{ .secretStoreKind | default "SecretStore" }}
  target:
    name: {{ .targetSecret }}
    creationPolicy: Owner
    {{- if .template }}
    template:
      type: {{ .template.type | default "Opaque" }}
      {{- if .template.metadata }}
      metadata:
        {{- toYaml .template.metadata | nindent 8 }}
      {{- end }}
      {{- if .template.data }}
      data:
        {{- toYaml .template.data | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if .data }}
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      {{- if .remoteRef.property }}
      property: {{ .remoteRef.property }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
  {{- range .dataFrom }}
  - extract:
      key: {{ .extract.key }}
      {{- if .extract.property }}
      property: {{ .extract.property }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}